apiVersion: apps/v1
kind: Deployment
metadata:
  name: clock-dep
  labels:
    app: clock-dep
    lang: go
spec:
  template:
    metadata:
      name: clock-pod
      labels:
        app: clock-pod
        lang: go
    spec:
      containers:
      - name: clock-pod
        image: hari24/clock
        ports:
         - containerPort: 8080
  replicas: 2
  selector:
    matchLabels:
      name: clock-pod
      lang: go
