apiVersion: v1
kind: Service
metadata:
	name: clock-serv
        labels:
                name: clock-serv
                lang: go
spec:
        type: LoadBalancer
        ports:
                - port: 8080
                  targetPort: 8080
        selector:
                name: clock-pod
                lang: go
